### ISSUE TITLE
test

### ISSUE THREAD

**Issue by SlavaKuntsov** [Bibimotik/project-storage#1]
реально чета писать могу

**Comment by SlavaKuntsov** [comment]
хуй, хаха

**Comment by Bararide** [comment]
жесть, что за сборище

**Comment by SlavaKuntsov** [comment]
### ну как будто бы да
а че будет когда делать начнем чета...

**Comment by Bararide** [comment]
в пн осуществляем сборище в офлайн режиме

**Comment by SlavaKuntsov** [comment]
где что когда
